name: Build and Deploy RSS Feed Page

on:
  schedule:
    - cron: '0 3 * * *'  # Ejecuta todos los días a las 3 AM UTC
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend and generate rss.json
        run: |
          ./mvnw clean package -f backend/pom.xml
          java -jar backend/target/*.jar
        env:
          SPRING_PROFILES_ACTIVE: prod

      - name: Move rss.json into frontend/public/
        run: |
          mkdir -p frontend/public
          cp output/rss.json frontend/public/rss.json

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
