name: Build and Deploy RSS Feed Page

on:
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch:    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1️⃣ BACKEND: Instalar Java y compilar + ejecutar
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make mvnw executable
        run: chmod +x ./backend/mvnw
        
      - name: Build and run backend to generate rss.json
        run: |
          cd backend
          ./mvnw clean package -DskipTests
          java -jar target/*.jar
  

      # 2️⃣ FRONTEND: Instalar Node, build y deploy
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # 3️⃣ DEPLOY a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build